/**
 * Build script for @investment-tracker/design-tokens
 *
 * Reads tokens from ./tokens/** (DTCG format — $value, $type, {ref.path}) and emits:
 *   build/css/tokens.css       — CSS custom properties. :root = primitives + light-semantic;
 *                                .dark = overrides for semantic.
 *   build/tailwind/tokens.js   — Tailwind-ready tokens object. Primitives concrete,
 *                                semantic colors as var() refs so dark mode switches.
 *   build/swift/Tokens.swift   — Swift enum with adaptive Colors (light/dark) for iOS.
 *   build/js/tokens.js         — Flat JS object of all tokens (light mode values).
 *   build/js/brand.js          — Product name, domain placeholders, legal meta.
 *
 * The tokens directory uses DTCG format so we can swap in Style Dictionary later
 * without touching the tokens themselves.
 *
 * Run: `npm run build`  (no deps needed — pure Node)
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = __dirname;
const BUILD_DIR = path.join(ROOT, 'build');

// ----------------------------------------------------------
// Token loading + ref resolution (DTCG-compatible)
// ----------------------------------------------------------

function readJson(relPath) {
  return JSON.parse(fs.readFileSync(path.join(ROOT, relPath), 'utf8'));
}

/** Deep-merge b into a (plain objects only). */
function merge(a, b) {
  for (const [k, v] of Object.entries(b)) {
    if (v && typeof v === 'object' && !Array.isArray(v) && a[k] && typeof a[k] === 'object') {
      merge(a[k], v);
    } else {
      a[k] = v;
    }
  }
  return a;
}

function loadTree(files) {
  const tree = {};
  for (const f of files) merge(tree, readJson(f));
  return tree;
}

/** Walks a token tree and returns a flat list of leaf tokens. */
function flatten(tree, prefix = []) {
  const out = [];
  for (const [k, v] of Object.entries(tree)) {
    if (k.startsWith('$')) continue;
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      if ('$value' in v) {
        out.push({
          path: [...prefix, k],
          value: v.$value,
          type: v.$type || null,
          description: v.$description || null,
        });
      } else {
        out.push(...flatten(v, [...prefix, k]));
      }
    }
  }
  return out;
}

/** Resolve {dot.path} refs against a flat map. Idempotent — loops until stable. */
function resolveRefs(tokens) {
  const byPath = Object.fromEntries(tokens.map((t) => [t.path.join('.'), t]));
  const REF = /\{([^{}]+)\}/g;

  function resolveValue(v, depth = 0) {
    if (depth > 12) throw new Error(`Ref depth exceeded at ${v}`);
    if (typeof v !== 'string') return v;
    if (!REF.test(v)) return v;
    REF.lastIndex = 0;
    return v.replace(REF, (_, ref) => {
      const target = byPath[ref];
      if (!target) throw new Error(`Unresolved ref: {${ref}}`);
      return resolveValue(target.value, depth + 1);
    });
  }

  for (const t of tokens) t.resolved = resolveValue(t.value);
  return tokens;
}

// ----------------------------------------------------------
// File writing helper
// ----------------------------------------------------------

function writeFile(relPath, content) {
  const full = path.join(BUILD_DIR, relPath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content);
  console.log(`  ✓ ${relPath}`);
}

function cleanBuild() {
  fs.rmSync(BUILD_DIR, { recursive: true, force: true });
  fs.mkdirSync(BUILD_DIR, { recursive: true });
}

// ----------------------------------------------------------
// Naming
// ----------------------------------------------------------

/** path → --color-background-primary (strip "semantic" root) */
function cssVarName(p) {
  return '--' + p.filter((x) => x !== 'semantic').join('-');
}

/** camelCase from path parts. Numeric-first keys get prefix. */
function camel(parts, numericPrefix = '') {
  return parts
    .map((p, i) => {
      const clean = String(p).replace(/[^a-zA-Z0-9]/g, '');
      if (i === 0 && /^\d/.test(clean)) return numericPrefix + clean;
      if (i === 0) return clean.charAt(0).toLowerCase() + clean.slice(1);
      return clean.charAt(0).toUpperCase() + clean.slice(1);
    })
    .join('');
}

// ----------------------------------------------------------
// Outputs
// ----------------------------------------------------------

function buildCss(primitives, light, dark) {
  const lines = [];
  lines.push('/**');
  lines.push(' * Design tokens for Portfolio');
  lines.push(' * Generated by packages/design-tokens/build.js — DO NOT EDIT BY HAND.');
  lines.push(' * Source: packages/design-tokens/tokens/**');
  lines.push(' */');
  lines.push('');
  lines.push(':root {');
  lines.push('  /* Primitives — identical across light/dark */');
  for (const t of primitives) {
    // Gradients emit as --gradient-{name}; others use their natural path.
    if (t.path[0] === 'gradient') {
      lines.push(`  --gradient-${t.path[1]}: ${t.resolved};`);
    } else {
      lines.push(`  ${cssVarName(t.path)}: ${t.resolved};`);
    }
  }
  lines.push('');
  lines.push('  /* Semantic — light mode */');
  for (const t of light) {
    lines.push(`  ${cssVarName(t.path)}: ${t.resolved};`);
  }
  lines.push('}');
  lines.push('');
  lines.push('.dark, [data-theme="dark"] {');
  lines.push('  /* Semantic — dark mode overrides */');
  for (const t of dark) {
    lines.push(`  ${cssVarName(t.path)}: ${t.resolved};`);
  }
  lines.push('}');
  writeFile('css/tokens.css', lines.join('\n') + '\n');
}

function buildTailwind(primitives, light) {
  // Primitive groups — concrete values keyed by their own sub-path
  const primByGroup = {};
  for (const t of primitives) {
    const [group, ...rest] = t.path;
    primByGroup[group] ||= [];
    primByGroup[group].push({ path: rest, value: t.resolved });
  }

  const nest = (list) => {
    const obj = {};
    for (const { path: p, value } of list) {
      let cursor = obj;
      for (let i = 0; i < p.length - 1; i++) {
        cursor[p[i]] = cursor[p[i]] || {};
        cursor = cursor[p[i]];
      }
      cursor[p[p.length - 1]] = value;
    }
    return obj;
  };

  // Color primitives (brand, neutral, green, red, amber, cyan, static)
  const colorPrims = (primByGroup.color || []).reduce((acc, t) => {
    const [sub, ...rest] = t.path;
    acc[sub] ||= [];
    acc[sub].push({ path: rest, value: t.value });
    return acc;
  }, {});
  const primColors = Object.fromEntries(
    Object.entries(colorPrims).map(([k, list]) => [k, nest(list)])
  );

  // Semantic colors → CSS var refs
  const semColorsByRoot = {};
  for (const t of light) {
    if (t.type !== 'color') continue;
    const parts = t.path.filter((p) => p !== 'semantic'); // e.g. ['background', 'primary']
    const [root, ...rest] = parts;
    semColorsByRoot[root] ||= [];
    semColorsByRoot[root].push({ path: rest, value: `var(${cssVarName(t.path)})` });
  }
  const semColors = Object.fromEntries(
    Object.entries(semColorsByRoot).map(([k, list]) => [k, nest(list)])
  );

  const colors = { ...primColors, ...semColors };

  const spacing = nest((primByGroup.spacing || []).map((t) => ({ path: t.path, value: t.value })));
  const borderRadius = nest((primByGroup.radius || []).map((t) => ({ path: t.path, value: t.value })));
  const boxShadow = nest((primByGroup.shadow || []).map((t) => ({ path: t.path, value: t.value })));

  const fontTokens = primByGroup.font || [];
  const fontFamily = nest(
    fontTokens
      .filter((t) => t.path[0] === 'family')
      .map((t) => ({ path: t.path.slice(1), value: t.value.split(',').map((s) => s.trim()) }))
  );
  const fontSize = nest(
    fontTokens.filter((t) => t.path[0] === 'size').map((t) => ({ path: t.path.slice(1), value: t.value }))
  );
  const fontWeight = nest(
    fontTokens.filter((t) => t.path[0] === 'weight').map((t) => ({ path: t.path.slice(1), value: String(t.value) }))
  );
  const lineHeight = nest(
    fontTokens.filter((t) => t.path[0] === 'lineHeight').map((t) => ({ path: t.path.slice(1), value: String(t.value) }))
  );
  const letterSpacing = nest(
    fontTokens.filter((t) => t.path[0] === 'letterSpacing').map((t) => ({ path: t.path.slice(1), value: t.value }))
  );

  const motionTokens = primByGroup.motion || [];
  const transitionDuration = nest(
    motionTokens.filter((t) => t.path[0] === 'duration').map((t) => ({ path: t.path.slice(1), value: t.value }))
  );
  const transitionTimingFunction = nest(
    motionTokens.filter((t) => t.path[0] === 'easing').map((t) => ({ path: t.path.slice(1), value: t.value }))
  );

  const tokens = {
    colors,
    spacing,
    borderRadius,
    boxShadow,
    fontFamily,
    fontSize,
    fontWeight,
    lineHeight,
    letterSpacing,
    transitionDuration,
    transitionTimingFunction,
  };

  const header = `/**
 * Tailwind design tokens for Portfolio — auto-generated from packages/design-tokens.
 * DO NOT EDIT BY HAND.
 *
 * Usage:
 *   import { tokens } from '@investment-tracker/design-tokens/tailwind';
 *   export default { theme: { extend: tokens } };
 */

`;
  writeFile('tailwind/tokens.js', `${header}export const tokens = ${JSON.stringify(tokens, null, 2)};\n`);
  writeFile(
    'tailwind/tokens.d.ts',
    `export declare const tokens: {
  colors: Record<string, any>;
  spacing: Record<string, string>;
  borderRadius: Record<string, string>;
  boxShadow: Record<string, string>;
  fontFamily: Record<string, string[]>;
  fontSize: Record<string, string>;
  fontWeight: Record<string, string>;
  lineHeight: Record<string, string>;
  letterSpacing: Record<string, string>;
  transitionDuration: Record<string, string>;
  transitionTimingFunction: Record<string, string>;
};
`
  );
}

/**
 * Tailwind v4 uses CSS-first configuration via the `@theme` directive.
 * Any `--<group>-<name>` declared inside `@theme` becomes a utility
 * (e.g. `--color-brand-500` → `bg-brand-500`, `text-brand-500`).
 *
 * We emit two blocks:
 *   1. `@theme` — primitives (concrete values): colors, spacing, radius,
 *      shadow, fonts, sizes, weights, leading, tracking, durations, easings.
 *   2. `@theme inline` — semantic aliases that reference the runtime CSS
 *      vars from `tokens.css`. This way `bg-background-primary` automatically
 *      flips when `.dark` is toggled on a parent.
 *
 * Dark mode: we configure `@custom-variant dark` to trigger on the `.dark`
 * class so shadcn-style dark: utilities work alongside the CSS-var flip.
 */
function buildTailwindThemeCss(primitives, light) {
  const lines = [];
  lines.push('/**');
  lines.push(' * Tailwind v4 theme for Portfolio — auto-generated.');
  lines.push(' * Source: packages/design-tokens/tokens/**');
  lines.push(' * DO NOT EDIT BY HAND.');
  lines.push(' *');
  lines.push(' * Usage (in your app CSS entry):');
  lines.push(' *   @import "tailwindcss";');
  lines.push(' *   @import "@investment-tracker/design-tokens/css";');
  lines.push(' *   @import "@investment-tracker/design-tokens/theme.css";');
  lines.push(' */');
  lines.push('');
  lines.push('@custom-variant dark (&:where(.dark, .dark *));');
  lines.push('');
  lines.push('@theme {');

  // --- Primitive colors: brand-500, neutral-50, green-600, etc.
  const primColors = primitives.filter((t) => t.type === 'color');
  lines.push('  /* Color primitives */');
  for (const t of primColors) {
    // path = ['color', 'brand', '500'] → --color-brand-500
    if (t.path[0] !== 'color') continue;
    const name = t.path.slice(1).join('-');
    // Skip `static` group's transparent (Tailwind has its own) but keep white/black
    if (name === 'static-transparent') continue;
    const key = name.startsWith('static-') ? name.replace('static-', '') : name;
    lines.push(`  --color-${key}: ${t.resolved};`);
  }

  // --- Spacing
  lines.push('');
  lines.push('  /* Spacing */');
  for (const t of primitives.filter((t) => t.path[0] === 'spacing')) {
    lines.push(`  --spacing-${t.path[1]}: ${t.resolved};`);
  }

  // --- Radius
  lines.push('');
  lines.push('  /* Radius */');
  for (const t of primitives.filter((t) => t.path[0] === 'radius')) {
    lines.push(`  --radius-${t.path[1]}: ${t.resolved};`);
  }

  // --- Shadow
  lines.push('');
  lines.push('  /* Shadow */');
  for (const t of primitives.filter((t) => t.path[0] === 'shadow')) {
    lines.push(`  --shadow-${t.path[1]}: ${t.resolved};`);
  }

  // --- Font families
  lines.push('');
  lines.push('  /* Font family */');
  for (const t of primitives.filter((t) => t.path[0] === 'font' && t.path[1] === 'family')) {
    lines.push(`  --font-${t.path[2]}: ${t.resolved};`);
  }

  // --- Font sizes (Tailwind v4 uses --text-* for font-size utilities)
  lines.push('');
  lines.push('  /* Font sizes */');
  for (const t of primitives.filter((t) => t.path[0] === 'font' && t.path[1] === 'size')) {
    lines.push(`  --text-${t.path[2]}: ${t.resolved};`);
  }

  // --- Font weights
  lines.push('');
  lines.push('  /* Font weights */');
  for (const t of primitives.filter((t) => t.path[0] === 'font' && t.path[1] === 'weight')) {
    lines.push(`  --font-weight-${t.path[2]}: ${t.resolved};`);
  }

  // --- Line heights (Tailwind v4 --leading-*)
  lines.push('');
  lines.push('  /* Line heights */');
  for (const t of primitives.filter((t) => t.path[0] === 'font' && t.path[1] === 'lineHeight')) {
    lines.push(`  --leading-${t.path[2]}: ${t.resolved};`);
  }

  // --- Letter spacing (Tailwind v4 --tracking-*)
  lines.push('');
  lines.push('  /* Letter spacing */');
  for (const t of primitives.filter((t) => t.path[0] === 'font' && t.path[1] === 'letterSpacing')) {
    lines.push(`  --tracking-${t.path[2]}: ${t.resolved};`);
  }

  // --- Motion
  lines.push('');
  lines.push('  /* Motion — durations */');
  for (const t of primitives.filter((t) => t.path[0] === 'motion' && t.path[1] === 'duration')) {
    lines.push(`  --duration-${t.path[2]}: ${t.resolved};`);
  }
  lines.push('');
  lines.push('  /* Motion — easings */');
  for (const t of primitives.filter((t) => t.path[0] === 'motion' && t.path[1] === 'easing')) {
    lines.push(`  --ease-${t.path[2]}: ${t.resolved};`);
  }

  // --- Gradients (emitted as plain custom properties; consumers use
  //     style={{ background: 'var(--gradient-ai)' }} or bg-[var(...)]).
  lines.push('');
  lines.push('  /* Gradients */');
  for (const t of primitives.filter((t) => t.path[0] === 'gradient')) {
    lines.push(`  --gradient-${t.path[1]}: ${t.resolved};`);
  }

  lines.push('}');
  lines.push('');

  // --- Semantic colors via inline refs to CSS vars from tokens.css
  lines.push('/* Semantic colors reference runtime CSS vars from tokens.css so they flip');
  lines.push(' * automatically when `.dark` is applied. */');
  lines.push('@theme inline {');
  const semColors = light.filter((t) => t.type === 'color');
  for (const t of semColors) {
    const parts = t.path.filter((p) => p !== 'semantic');
    const name = parts.join('-');
    lines.push(`  --color-${name}: var(${cssVarName(t.path)});`);
  }
  lines.push('}');
  lines.push('');

  writeFile('tailwind/theme.css', lines.join('\n'));
}

function buildSwift(primitives, light, dark) {
  const parseRgba = (v) => {
    const m = String(v).match(/rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+))?\)/);
    if (!m) return null;
    return { r: +m[1], g: +m[2], b: +m[3], a: m[4] !== undefined ? +m[4] : 1 };
  };
  const isHex = (v) => typeof v === 'string' && v.startsWith('#');

  const colorInit = (val) => {
    if (val === 'transparent') return 'Color.clear';
    if (isHex(val)) {
      const v = val.replace('#', '').toLowerCase();
      if (v.length === 6) return `Color(hex: 0x${v})`;
      if (v.length === 8) {
        const rgb = v.slice(0, 6);
        const a = parseInt(v.slice(6), 16) / 255;
        return `Color(hex: 0x${rgb}, opacity: ${a.toFixed(3)})`;
      }
    }
    const rgba = parseRgba(val);
    if (rgba) {
      const hex = ((rgba.r << 16) | (rgba.g << 8) | rgba.b).toString(16).padStart(6, '0');
      return `Color(hex: 0x${hex}, opacity: ${rgba.a})`;
    }
    return `Color(/* UNPARSED: ${val} */)`;
  };

  const lines = [];
  lines.push(`// Design tokens for Portfolio — auto-generated from packages/design-tokens.`);
  lines.push(`// Source: packages/design-tokens/tokens/**`);
  lines.push(`// DO NOT EDIT BY HAND.`);
  lines.push(`//`);
  lines.push(`// Usage:`);
  lines.push(`//   import SwiftUI`);
  lines.push(`//   Tokens.Color.interactivePrimary  // adaptive (light/dark)`);
  lines.push(`//   Tokens.Spacing.s4                // 16pt`);
  lines.push(`//   Tokens.Radius.lg                 // 8pt`);
  lines.push(``);
  lines.push(`import SwiftUI`);
  lines.push(``);
  lines.push(`public enum Tokens {`);
  lines.push(``);
  lines.push(`    // MARK: - Colors`);
  lines.push(``);
  lines.push(`    public enum Color {`);
  lines.push(`        // Primitives — static (identical across schemes)`);

  const primColors = primitives.filter((t) => t.type === 'color');
  for (const t of primColors) {
    // drop "color" prefix from path for naming
    const name = camel(t.path.slice(1));
    if (!name) continue;
    lines.push(`        public static let ${name} = ${colorInit(t.resolved)}`);
  }

  lines.push(``);
  lines.push(`        // Semantic — adaptive via ColorScheme`);
  const lightSem = light.filter((t) => t.type === 'color');
  const darkByKey = Object.fromEntries(
    dark.filter((t) => t.type === 'color').map((t) => [t.path.join('.'), t.resolved])
  );
  for (const t of lightSem) {
    const parts = t.path.filter((p) => p !== 'semantic');
    const name = camel(parts);
    const lightV = t.resolved;
    const darkV = darkByKey[t.path.join('.')] ?? lightV;
    lines.push(
      `        public static let ${name} = adaptiveColor(light: ${colorInit(lightV)}, dark: ${colorInit(darkV)})`
    );
  }
  lines.push(`    }`);
  lines.push(``);

  // Spacing
  lines.push(`    // MARK: - Spacing (pt)`);
  lines.push(``);
  lines.push(`    public enum Spacing {`);
  for (const t of primitives.filter((t) => t.path[0] === 'spacing')) {
    const key = t.path[1];
    const val = String(t.resolved).replace('px', '');
    const label = /^\d+$/.test(key) ? `s${key}` : `s${key.charAt(0).toUpperCase()}${key.slice(1)}`;
    lines.push(`        public static let ${label}: CGFloat = ${val}`);
  }
  lines.push(`    }`);
  lines.push(``);

  // Radius
  lines.push(`    // MARK: - Radius (pt)`);
  lines.push(``);
  lines.push(`    public enum Radius {`);
  for (const t of primitives.filter((t) => t.path[0] === 'radius')) {
    const key = t.path[1];
    const val = String(t.resolved).replace('px', '');
    const label = /^\d/.test(key) ? `r${key}` : key;
    lines.push(`        public static let ${label}: CGFloat = ${val}`);
  }
  lines.push(`    }`);
  lines.push(``);

  // FontSize
  lines.push(`    // MARK: - Font sizes (pt)`);
  lines.push(``);
  lines.push(`    public enum FontSize {`);
  for (const t of primitives.filter((t) => t.path[0] === 'font' && t.path[1] === 'size')) {
    const key = t.path[2];
    const val = String(t.resolved).replace('px', '');
    const label = /^\d/.test(key) ? `fs${key}` : key;
    lines.push(`        public static let ${label}: CGFloat = ${val}`);
  }
  lines.push(`    }`);
  lines.push(``);

  // FontWeight
  lines.push(`    // MARK: - Font weights`);
  lines.push(``);
  lines.push(`    public enum FontWeight {`);
  const weightMap = { 400: '.regular', 500: '.medium', 600: '.semibold', 700: '.bold' };
  for (const t of primitives.filter((t) => t.path[0] === 'font' && t.path[1] === 'weight')) {
    const key = t.path[2];
    const mapped = weightMap[String(t.resolved)] || `.custom(${t.resolved})`;
    lines.push(`        public static let ${key}: Font.Weight = ${mapped}`);
  }
  lines.push(`    }`);
  lines.push(``);

  // Motion
  lines.push(`    // MARK: - Motion`);
  lines.push(``);
  lines.push(`    public enum Motion {`);
  lines.push(`        public enum Duration {`);
  for (const t of primitives.filter((t) => t.path[0] === 'motion' && t.path[1] === 'duration')) {
    const key = t.path[2];
    const ms = parseInt(String(t.resolved).replace('ms', ''), 10);
    lines.push(`            public static let ${key}: TimeInterval = ${(ms / 1000).toFixed(3)}`);
  }
  lines.push(`        }`);
  lines.push(`    }`);
  lines.push(`}`);
  lines.push(``);

  // Helpers
  lines.push(`// MARK: - Helpers`);
  lines.push(``);
  lines.push(`public extension Color {`);
  lines.push(`    /// Init Color with hex int (e.g. 0x6D28D9) and optional opacity.`);
  lines.push(`    init(hex: UInt32, opacity: Double = 1.0) {`);
  lines.push(`        let r = Double((hex >> 16) & 0xFF) / 255.0`);
  lines.push(`        let g = Double((hex >> 8) & 0xFF) / 255.0`);
  lines.push(`        let b = Double(hex & 0xFF) / 255.0`);
  lines.push(`        self.init(.sRGB, red: r, green: g, blue: b, opacity: opacity)`);
  lines.push(`    }`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`/// Returns a color that adapts to the current color scheme.`);
  lines.push(`public func adaptiveColor(light: Color, dark: Color) -> Color {`);
  lines.push(`    #if canImport(UIKit)`);
  lines.push(`    return Color(UIColor { trait in`);
  lines.push(`        trait.userInterfaceStyle == .dark ? UIColor(dark) : UIColor(light)`);
  lines.push(`    })`);
  lines.push(`    #else`);
  lines.push(`    return light`);
  lines.push(`    #endif`);
  lines.push(`}`);
  lines.push(``);

  writeFile('swift/Tokens.swift', lines.join('\n'));
}

function buildJs(primitives, light) {
  const data = {};
  for (const t of [...primitives, ...light]) {
    const parts = t.path.filter((p) => p !== 'semantic');
    let cursor = data;
    for (let i = 0; i < parts.length - 1; i++) {
      cursor[parts[i]] = cursor[parts[i]] || {};
      cursor = cursor[parts[i]];
    }
    cursor[parts[parts.length - 1]] = t.resolved;
  }
  writeFile(
    'js/tokens.js',
    `/** Runtime design tokens — light mode values. Do NOT edit. */\n\nexport const tokens = ${JSON.stringify(data, null, 2)};\n`
  );
  writeFile('js/tokens.d.ts', `export declare const tokens: Record<string, any>;\n`);
}

function buildBrand() {
  const brand = readJson('tokens/brand.json').brand;
  function unwrap(node) {
    if (node && typeof node === 'object') {
      if ('$value' in node) return node.$value;
      const out = {};
      for (const [k, v] of Object.entries(node)) {
        if (k.startsWith('$')) continue;
        out[k] = unwrap(v);
      }
      return out;
    }
    return node;
  }
  const data = unwrap(brand);

  const header = `/**
 * Brand metadata for Portfolio. Single source of truth.
 *
 * Import product name, domains, legal info from here — NEVER hardcode
 * "Portfolio" in components or copy. When the product name changes,
 * update tokens/brand.json only, then re-run build.
 *
 *   import { brand, PRODUCT_NAME } from '@investment-tracker/design-tokens/brand';
 */

`;
  writeFile(
    'js/brand.js',
    `${header}export const brand = ${JSON.stringify(data, null, 2)};\n\nexport const PRODUCT_NAME = brand.productName;\nexport const PRODUCT_TAGLINE = brand.tagline;\n`
  );

  writeFile(
    'js/brand.d.ts',
    `export declare const brand: {
  readonly productName: string;
  readonly productNameShort: string;
  readonly tagline: string;
  readonly legalName: string;
  readonly domain: { readonly web: string; readonly api: string; readonly marketing: string };
  readonly email: { readonly support: string; readonly legal: string; readonly noreply: string };
  readonly logo: { readonly variants: readonly string[] };
};
export declare const PRODUCT_NAME: string;
export declare const PRODUCT_TAGLINE: string;
`
  );
}

// ----------------------------------------------------------
// Main
// ----------------------------------------------------------

function main() {
  console.log('Building @investment-tracker/design-tokens...\n');
  cleanBuild();

  const primitiveFiles = fs
    .readdirSync(path.join(ROOT, 'tokens/primitives'))
    .filter((f) => f.endsWith('.json'))
    .map((f) => `tokens/primitives/${f}`);

  const primitiveTree = loadTree(primitiveFiles);
  const lightTree = loadTree([...primitiveFiles, 'tokens/semantic/light.json']);
  const darkTree = loadTree([...primitiveFiles, 'tokens/semantic/dark.json']);

  const primitives = resolveRefs(flatten(primitiveTree));
  const lightAll = resolveRefs(flatten(lightTree));
  const darkAll = resolveRefs(flatten(darkTree));

  const light = lightAll.filter((t) => t.path[0] === 'semantic');
  const dark = darkAll.filter((t) => t.path[0] === 'semantic');

  console.log(`  Loaded ${primitives.length} primitives, ${light.length} light semantic, ${dark.length} dark semantic`);
  console.log('');

  console.log('CSS:');
  buildCss(primitives, light, dark);
  console.log('');

  console.log('Tailwind (JS object):');
  buildTailwind(primitives, light);
  console.log('');

  console.log('Tailwind (v4 @theme CSS):');
  buildTailwindThemeCss(primitives, light);
  console.log('');

  console.log('Swift:');
  buildSwift(primitives, light, dark);
  console.log('');

  console.log('JS:');
  buildJs(primitives, light);
  console.log('');

  console.log('Brand:');
  buildBrand();
  console.log('');

  console.log('Done. Outputs in ./build');
}

try {
  main();
} catch (err) {
  console.error('Build failed:', err.message);
  console.error(err.stack);
  process.exit(1);
}
