const brandScale = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950] as const;
const neutralScale = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950] as const;

const semanticBg = [
  'background-primary',
  'background-secondary',
  'background-tertiary',
  'background-elevated',
] as const;

const semanticText = [
  'text-primary',
  'text-secondary',
  'text-tertiary',
  'text-muted',
  'text-brand',
] as const;

const stateColors = ['positive', 'negative', 'warning', 'info'] as const;

const spacingKeys = ['1', '2', '3', '4', '5', '6', '8', '10', '12', '16'] as const;
const radiusKeys = ['sm', 'md', 'lg', 'xl', '2xl', 'full'] as const;
const shadowKeys = ['xs', 'sm', 'md', 'lg', 'xl', 'ai'] as const;

const displayScale = [
  ['display-xl', '72px / 1.0 / -0.04em', 'tracking-tightest'],
  ['display-lg', '48px / 1.1 / -0.03em', 'tracking-tighter'],
  ['display-md', '36px / 1.15 / -0.02em', 'tracking-tight'],
  ['display-sm', '28px / 1.2 / -0.02em', 'tracking-tight'],
] as const;

const textScale = [
  ['heading-lg', '20px / 1.3 / 600', ''],
  ['heading-md', '18px / 1.4 / 600', ''],
  ['body-lg', '16px / 1.5 / 400', ''],
  ['body-md', '14px / 1.5 / 400', ''],
  ['body-sm', '13px / 1.5 / 400', ''],
  ['caption', '12px / 1.4 / 500 / UPPERCASE', 'tracking-caption uppercase'],
] as const;

const motionDurations = ['fast', 'base', 'slow', 'slower', 'count-up', 'shimmer'] as const;
const motionEasings = ['default', 'in', 'out', 'inOut', 'spring', 'exp-out'] as const;

const gradientKeys = [
  ['brand', 'Primary violet — hero KPI bg'],
  ['ai', 'AI accent — chat hero, Ask AI, FAB'],
  ['success', 'Success confirmations'],
  ['danger', 'Destructive confirmations'],
  ['chart-area', 'Area chart fill 30→0'],
  ['shimmer', 'Loading sweep'],
  ['plus', 'Plan badge — Plus'],
  ['pro', 'Plan badge — Pro'],
] as const;

export function FoundationsSection() {
  return (
    <section id="foundations" className="space-y-10 scroll-mt-20">
      <div className="space-y-1">
        <h2 className="text-2xl font-semibold tracking-tight">Foundations</h2>
        <p className="text-sm text-text-secondary">
          Primitives + semantic aliases generated by packages/design-tokens.
        </p>
      </div>

      <SubSection title="Brand scale — #6D28D9 (violet-700)">
        <div className="grid grid-cols-11 gap-1">
          {brandScale.map((n) => (
            <div key={n} className="space-y-1">
              <div
                className="h-12 w-full rounded-sm border border-border-subtle"
                style={{ backgroundColor: `var(--color-brand-${n})` }}
              />
              <div className="font-mono text-[10px] text-text-tertiary">{n}</div>
            </div>
          ))}
        </div>
      </SubSection>

      <SubSection title="Neutral scale (slate, per brief §3.1)">
        <div className="grid grid-cols-11 gap-1">
          {neutralScale.map((n) => (
            <div key={n} className="space-y-1">
              <div
                className="h-12 w-full rounded-sm border border-border-subtle"
                style={{ backgroundColor: `var(--color-neutral-${n})` }}
              />
              <div className="font-mono text-[10px] text-text-tertiary">{n}</div>
            </div>
          ))}
        </div>
      </SubSection>

      <SubSection title="Semantic — background">
        <div className="grid grid-cols-4 gap-4">
          {semanticBg.map((name) => (
            <div key={name} className="space-y-2">
              <div
                className="h-16 w-full rounded-md border border-border-default"
                style={{ backgroundColor: `var(--color-${name})` }}
              />
              <div className="font-mono text-xs text-text-tertiary">{name}</div>
            </div>
          ))}
        </div>
      </SubSection>

      <SubSection title="Semantic — text">
        <div className="space-y-2">
          {semanticText.map((name) => (
            <p key={name} className="text-base" style={{ color: `var(--color-${name})` }}>
              <span className="font-mono text-xs mr-3 text-text-tertiary">{name}</span>
              The quick brown fox jumps over the lazy dog — 1,234,567.89
            </p>
          ))}
        </div>
      </SubSection>

      <SubSection title="State colors">
        <div className="grid grid-cols-4 gap-4">
          {stateColors.map((s) => (
            <div key={s} className="space-y-2">
              <div
                className="h-12 w-full rounded-sm"
                style={{ backgroundColor: `var(--color-state-${s}-default)` }}
              />
              <div
                className="h-6 w-full rounded-sm"
                style={{ backgroundColor: `var(--color-state-${s}-subtle)` }}
              />
              <div className="font-mono text-xs text-text-tertiary">state.{s}</div>
            </div>
          ))}
        </div>
      </SubSection>

      <SubSection title="Portfolio — gain / loss / neutral">
        <div className="grid grid-cols-3 gap-4">
          {(['gain', 'loss', 'neutral'] as const).map((k) => (
            <div key={k} className="space-y-2">
              <div
                className="h-12 w-full rounded-sm"
                style={{ backgroundColor: `var(--color-portfolio-${k}-default)` }}
              />
              <div className="font-mono text-xs text-text-tertiary">portfolio.{k}</div>
            </div>
          ))}
        </div>
      </SubSection>

      <SubSection title="Typography — Display scale (brief §3.2)">
        <div className="space-y-4">
          {displayScale.map(([name, meta, extra]) => (
            <div key={name} className="space-y-1">
              <p
                className={`font-bold ${extra}`}
                style={{ fontSize: `var(--text-${name})`, lineHeight: '1.1' }}
              >
                $127,450.32
              </p>
              <p className="font-mono text-[11px] text-text-tertiary">
                {name} · {meta}
              </p>
            </div>
          ))}
        </div>
      </SubSection>

      <SubSection title="Typography — Heading / body / caption">
        <div className="space-y-2">
          {textScale.map(([name, meta, extra]) => (
            <div key={name} className="flex items-baseline gap-4">
              <p className={`${extra}`} style={{ fontSize: `var(--text-${name})` }}>
                Your portfolio is up <span className="tabular-nums">+$1,204 (+0.95%)</span> today
              </p>
              <span className="font-mono text-[11px] text-text-tertiary whitespace-nowrap">
                {name} · {meta}
              </span>
            </div>
          ))}
        </div>
      </SubSection>

      <SubSection title="Tabular-nums (money / pct)">
        <div className="space-y-1 font-mono">
          <p className="text-base tabular-nums">$127,450.32  +$1,204.00  +0.95%</p>
          <p className="text-base tabular-nums">$089,201.11  -$432.10   -0.48%</p>
          <p className="text-base">$127,450.32  +$1,204.00  +0.95% (non-tabular)</p>
          <p className="text-[11px] text-text-tertiary">
            Tabular-nums keeps digit columns aligned — crucial for tables and hero counters.
          </p>
        </div>
      </SubSection>

      <SubSection title="Spacing scale">
        <div className="flex items-end gap-2">
          {spacingKeys.map((k) => (
            <div key={k} className="flex flex-col items-center gap-1">
              <div
                className="rounded bg-brand-500"
                style={{ width: `var(--spacing-${k})`, height: `var(--spacing-${k})` }}
              />
              <span className="font-mono text-[10px] text-text-tertiary">{k}</span>
            </div>
          ))}
        </div>
      </SubSection>

      <SubSection title="Border radius (per brief §3.4)">
        <div className="flex items-end gap-4">
          {radiusKeys.map((k) => (
            <div key={k} className="flex flex-col items-center gap-1">
              <div
                className="h-14 w-14 border border-border-default bg-background-secondary"
                style={{ borderRadius: `var(--radius-${k})` }}
              />
              <span className="font-mono text-[10px] text-text-tertiary">{k}</span>
            </div>
          ))}
        </div>
      </SubSection>

      <SubSection title="Shadow (xs + ai added)">
        <div className="flex gap-6 flex-wrap">
          {shadowKeys.map((k) => (
            <div key={k} className="flex flex-col items-center gap-2">
              <div
                className="h-16 w-24 rounded-md bg-background-elevated border border-border-subtle"
                style={{ boxShadow: `var(--shadow-${k})` }}
              />
              <span className="font-mono text-[10px] text-text-tertiary">{k}</span>
            </div>
          ))}
        </div>
      </SubSection>

      <SubSection title="Motion — durations">
        <div className="flex gap-3 flex-wrap">
          {motionDurations.map((d) => (
            <MotionDemo key={d} durationVar={d} />
          ))}
        </div>
      </SubSection>

      <SubSection title="Motion — easings">
        <div className="flex gap-3 flex-wrap">
          {motionEasings.map((e) => (
            <div
              key={e}
              className="flex h-9 items-center gap-2 rounded-full border border-border-subtle bg-background-secondary px-3"
            >
              <span
                className="inline-block h-2 w-2 rounded-full bg-brand-500 transition-transform duration-[400ms] hover:translate-x-6"
                style={{ transitionTimingFunction: `var(--ease-${e})` }}
              />
              <span className="font-mono text-xs text-text-secondary">ease-{e}</span>
            </div>
          ))}
        </div>
        <p className="text-[11px] text-text-tertiary">Hover a pill to animate the dot.</p>
      </SubSection>

      <SubSection title="Gradients (use sparingly — brief §3.1)">
        <div className="grid grid-cols-4 gap-3">
          {gradientKeys.map(([k, desc]) => (
            <div key={k} className="space-y-1">
              <div
                className="h-20 w-full rounded-md border border-border-subtle"
                style={{ background: `var(--gradient-${k})` }}
              />
              <div className="font-mono text-[10px] text-text-tertiary">gradient-{k}</div>
              <div className="text-[11px] text-text-secondary">{desc}</div>
            </div>
          ))}
        </div>
      </SubSection>
    </section>
  );
}

function SubSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-3">
      <h3 className="text-sm font-semibold uppercase tracking-wide text-text-tertiary">{title}</h3>
      {children}
    </div>
  );
}

function MotionDemo({ durationVar }: { durationVar: string }) {
  return (
    <button
      type="button"
      className="group flex h-9 items-center gap-2 rounded-full border border-border-subtle bg-background-secondary px-3"
    >
      <span
        className="block h-2 w-8 rounded-full bg-brand-500 origin-left scale-x-100 group-hover:scale-x-[1.6] ease-out"
        style={{
          transitionDuration: `var(--duration-${durationVar})`,
          transitionProperty: 'transform',
        }}
      />
      <span className="font-mono text-xs text-text-secondary">duration-{durationVar}</span>
    </button>
  );
}
