const brandScale = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950] as const;
const neutralScale = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950] as const;

const semanticBg = [
  'background-primary',
  'background-secondary',
  'background-tertiary',
  'background-elevated',
] as const;

const semanticText = [
  'text-primary',
  'text-secondary',
  'text-tertiary',
  'text-muted',
  'text-brand',
] as const;

const stateColors = ['positive', 'negative', 'warning', 'info'] as const;

const spacingKeys = ['1', '2', '3', '4', '5', '6', '8', '10', '12', '16'] as const;
const radiusKeys = ['sm', 'md', 'lg', 'xl', '2xl', 'full'] as const;
const shadowKeys = ['sm', 'md', 'lg', 'xl'] as const;

export function FoundationsSection() {
  return (
    <section id="foundations" className="space-y-10 scroll-mt-20">
      <div className="space-y-1">
        <h2 className="text-2xl font-semibold tracking-tight">Foundations</h2>
        <p className="text-sm text-text-secondary">
          Primitives and semantic aliases generated by Style Dictionary.
        </p>
      </div>

      <SubSection title="Brand scale — accent #6D28D9 (violet-700)">
        <div className="grid grid-cols-11 gap-1">
          {brandScale.map((n) => (
            <div key={n} className="space-y-1">
              <div
                className="h-12 w-full rounded-md border border-border-subtle"
                style={{ backgroundColor: `var(--color-brand-${n})` }}
              />
              <div className="font-mono text-[10px] text-text-tertiary">{n}</div>
            </div>
          ))}
        </div>
      </SubSection>

      <SubSection title="Neutral scale">
        <div className="grid grid-cols-11 gap-1">
          {neutralScale.map((n) => (
            <div key={n} className="space-y-1">
              <div
                className="h-12 w-full rounded-md border border-border-subtle"
                style={{ backgroundColor: `var(--color-neutral-${n})` }}
              />
              <div className="font-mono text-[10px] text-text-tertiary">{n}</div>
            </div>
          ))}
        </div>
      </SubSection>

      <SubSection title="Semantic — background">
        <div className="grid grid-cols-4 gap-4">
          {semanticBg.map((name) => (
            <div key={name} className="space-y-2">
              <div
                className="h-16 w-full rounded-lg border border-border-default"
                style={{ backgroundColor: `var(--color-${name})` }}
              />
              <div className="font-mono text-xs text-text-tertiary">{name}</div>
            </div>
          ))}
        </div>
      </SubSection>

      <SubSection title="Semantic — text">
        <div className="space-y-2">
          {semanticText.map((name) => (
            <p key={name} className="text-base" style={{ color: `var(--color-${name})` }}>
              <span className="font-mono text-xs mr-3 text-text-tertiary">{name}</span>
              The quick brown fox jumps over the lazy dog — 1,234,567.89
            </p>
          ))}
        </div>
      </SubSection>

      <SubSection title="State colors">
        <div className="grid grid-cols-4 gap-4">
          {stateColors.map((s) => (
            <div key={s} className="space-y-2">
              <div
                className="h-12 w-full rounded-md"
                style={{ backgroundColor: `var(--color-state-${s}-default)` }}
              />
              <div
                className="h-6 w-full rounded-md"
                style={{ backgroundColor: `var(--color-state-${s}-subtle)` }}
              />
              <div className="font-mono text-xs text-text-tertiary">state.{s}</div>
            </div>
          ))}
        </div>
      </SubSection>

      <SubSection title="Portfolio — gain / loss / neutral">
        <div className="grid grid-cols-3 gap-4">
          {(['gain', 'loss', 'neutral'] as const).map((k) => (
            <div key={k} className="space-y-2">
              <div
                className="h-12 w-full rounded-md"
                style={{ backgroundColor: `var(--color-portfolio-${k}-default)` }}
              />
              <div className="font-mono text-xs text-text-tertiary">portfolio.{k}</div>
            </div>
          ))}
        </div>
      </SubSection>

      <SubSection title="Typography — Geist Sans + Geist Mono">
        <div className="space-y-3">
          <p className="text-4xl font-semibold tracking-tight">4xl · Headline</p>
          <p className="text-2xl font-semibold">2xl · Section</p>
          <p className="text-lg">lg · Subheader</p>
          <p className="text-base">base · Body text. This paragraph demonstrates default sizing.</p>
          <p className="text-sm text-text-secondary">sm · Secondary body.</p>
          <p className="text-xs text-text-tertiary">xs · Captions and meta.</p>
          <p className="font-mono text-base tabular-nums">
            Geist Mono · $12,345.67 · +1.73% · AAPL
          </p>
        </div>
      </SubSection>

      <SubSection title="Spacing scale">
        <div className="flex items-end gap-2">
          {spacingKeys.map((k) => (
            <div key={k} className="flex flex-col items-center gap-1">
              <div
                className="rounded bg-brand-500"
                style={{ width: `var(--spacing-${k})`, height: `var(--spacing-${k})` }}
              />
              <span className="font-mono text-[10px] text-text-tertiary">{k}</span>
            </div>
          ))}
        </div>
      </SubSection>

      <SubSection title="Border radius">
        <div className="flex items-end gap-4">
          {radiusKeys.map((k) => (
            <div key={k} className="flex flex-col items-center gap-1">
              <div
                className="h-14 w-14 border border-border-default bg-background-secondary"
                style={{ borderRadius: `var(--radius-${k})` }}
              />
              <span className="font-mono text-[10px] text-text-tertiary">{k}</span>
            </div>
          ))}
        </div>
      </SubSection>

      <SubSection title="Shadow">
        <div className="flex gap-6">
          {shadowKeys.map((k) => (
            <div key={k} className="flex flex-col items-center gap-2">
              <div
                className="h-16 w-24 rounded-lg bg-background-elevated"
                style={{ boxShadow: `var(--shadow-${k})` }}
              />
              <span className="font-mono text-[10px] text-text-tertiary">{k}</span>
            </div>
          ))}
        </div>
      </SubSection>
    </section>
  );
}

function SubSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-3">
      <h3 className="text-sm font-semibold uppercase tracking-wide text-text-tertiary">{title}</h3>
      {children}
    </div>
  );
}
